### ISSUE TITLE
Tensors created using torch.from_numpy should be explicitly transfered to the default device

### ISSUE THREAD

**Issue by leonschindler97** [MKHoffmann/icpReconstructor#5]
When using the torch.from_numpy() method the default device is ignored. This means the tensors created using this method must be explicitly transferred to the set default device. 
This allows the user to set the torch default device in advance to different devices other than the CPU. 

**Proposed fix**
Use torch.from_numpy(...).to(torch.get_default_device()) as workaround.

**Comment by MKHoffmann** [comment]
torch.get_default_device() is only avaible in torch 2.3, we will keep it like this for now and have later versions require torch 2.3.
